export const ModVersion = modVersion;
export const ModName = modName;
export const ModRepo = modRepo;
export const ModIdentifier = modIdentifier;
export const PublicURL = publicURL;

// Littlish Club
export const AccessRight = {
  MANAGE_DIAPER: "MANAGE_DIAPER",
  MANAGE_RULES: "MANAGE_RULES",
  TURN_RULE_STRICT_MODE: "TURN_RULE_STRICT_MODE",
  DELETE_NOTES: "DELETE_NOTES",
  MANAGE_APPEARANCE: "MANAGE_APPEARANCE",
  MANAGE_CAREGIVERS_ACCESS_RIGHTS: "MANAGE_CAREGIVERS_ACCESS_RIGHTS",
  TURN_PREVENT_BABY_FROM_CHANGING_CAREGIVERS_LIST: "TURN_PREVENT_BABY_FROM_CHANGING_CAREGIVERS_LIST",
  CHANGE_CAREGIVERS_LIST: "CHANGE_CAREGIVERS_LIST",
} as const;

export const RuleId = {
  PREVENT_TAKING_ABDL_ITEMS_OFF: 1000,
  PREVENT_USING_ADMIN_POWERS: 1001,
  PREVENT_RESISTING_URGES: 1002,
  ABDL_INVENTORY: 1003,
  SPEAK_LIKE_BABY: 1004,
  WALK_LIKE_BABY: 1005,
  CANT_GO_SHOP_ALONE: 1006,
  FALL_SLEEP_AFTER_MILK_BOTTLE: 1007,
  DECREASE_SIZE: 1008,
  DISABLE_RESET_SETTINGS_BUTTON: 1009,
} as const;
